title: "å¤§é½è´¢ç»å¿«è®¯"
description: "ä½¿ç”¨ /docs è·¯å¾„æ„å»ºï¼Œå¯ç»‘å®šè‡ªå®šä¹‰åŸŸå"
theme: jekyll-theme-cayman        # GitHub Pages å®˜æ–¹ä¸»é¢˜ä¹‹ä¸€
baseurl: "/stocknews"               # ğŸ‘ˆ å¦‚æœä»“åº“ä¸æ˜¯ username.github.ioï¼Œè¯·å†™ä»“åº“å
#url: "https://yourdomain.com"     # ğŸ‘ˆ è‹¥ä½¿ç”¨è‡ªå®šä¹‰åŸŸåï¼Œå¡«æ‚¨çš„åŸŸåï¼Œå¦åˆ™å¯çœç•¥